import { defineNuxtPlugin, useRuntimeConfig, useHead } from '#app'
import { getOrCreateConsentRuntime, mergeTranslationConfigs, buildPrefetchScript } from 'c15t'
import type { C15tStore } from './utils/store'
import type { C15tRuntimeConfig } from './utils/types'
// Virtual template, generated by module.ts via addTemplate.
import { translations as bundledTranslations } from '#build/nuxt-c15t-translations.mjs'

export default defineNuxtPlugin((nuxtApp) => {
  const runtimeConfig = useRuntimeConfig()
  const config = runtimeConfig.public.c15t as C15tRuntimeConfig

  // Mode mapping — 'self-hosted' is functionally equivalent to 'hosted' from
  // c15t's perspective (both need a backendURL). We keep the distinction in
  // our own config for clarity, but collapse it here.
  const modeConfig = config.mode === 'offline'
    ? { mode: 'offline' as const }
    : { mode: 'hosted' as const, backendURL: config.backendURL }

  const hasNetworkRules = !!config.networkBlocker?.rules?.length
  const hasOfflinePolicyPacks = config.mode === 'offline' && !!config.policyPacks?.length

  const { consentStore } = getOrCreateConsentRuntime({
    ...modeConfig,
    consentCategories: config.consentCategories,
    ...(config.countryOverride && { overrides: { country: config.countryOverride } }),
    iframeBlockerConfig: config.iframeBlocking ? {} : { disableAutomaticBlocking: true },
    ...(hasNetworkRules && {
      networkBlocker: {
        enabled: config.networkBlocker!.enabled !== false,
        logBlockedRequests: config.networkBlocker!.logBlockedRequests !== false,
        rules: config.networkBlocker!.rules,
      },
    }),
    ...(hasOfflinePolicyPacks && {
      offlinePolicy: { policyPacks: config.policyPacks! },
    }),
  }, {
    pkg: 'nuxt-c15t',
    version: config.version || '0.0.0',
  })

  // Apply custom translations once the store finishes async init.
  // Can't pass at init time — getOrCreateConsentRuntime doesn't merge them.
  // Can't apply synchronously — initConsentManager resets translationConfig.
  const customTranslations = (bundledTranslations || {}) as { translations?: Record<string, unknown> }
  if (customTranslations.translations && Object.keys(customTranslations.translations).length > 0) {
    const customLangs = Object.keys(customTranslations.translations)

    // Re-apply custom translations whenever the store re-inits (e.g. after
    // setLanguage triggers initConsentManager which resets translationConfig).
    // Only apply if our languages are missing — prevents infinite loops.
    consentStore.subscribe((state) => {
      if (state.isLoadingConsentInfo) return
      const currentLangs = Object.keys(state.translationConfig?.translations || {})
      const missing = customLangs.some(l => !currentLangs.includes(l))
      if (missing) {
        const merged = mergeTranslationConfigs(state.translationConfig, customTranslations as Parameters<typeof mergeTranslationConfigs>[1])
        consentStore.getState().setTranslationConfig(merged)
      }
    })
  }

  // Inject prefetch script for hosted/self-hosted modes.
  if (config.prefetchScript && config.mode !== 'offline' && config.backendURL) {
    const scriptContent = buildPrefetchScript({
      backendURL: config.backendURL,
      ...(config.countryOverride && { overrides: { country: config.countryOverride } }),
    })

    const nonce = config.readCspNonceFromRuntimeConfig
      ? (runtimeConfig.public as { cspNonce?: string }).cspNonce
      : config.cspNonce

    useHead({
      script: [{
        innerHTML: scriptContent,
        tagPosition: 'head',
        ...(nonce ? { nonce } : {}),
      }],
    })
  }

  // Fire the runtime-ready hook so apps/other modules can react.
  // callHook may return void or a Promise depending on registered handlers,
  // so we normalise via Promise.resolve() before attaching the catch.
  Promise.resolve(
    (nuxtApp.callHook as (name: string, payload: unknown) => unknown)('c15t:ready', { mode: config.mode }),
  ).catch(() => {
    // swallow — a failing hook handler shouldn't crash the plugin.
  })

  return {
    provide: {
      c15tStore: consentStore as unknown as C15tStore,
    },
  }
})
